name: Grevm Ethereum

on:
  pull_request:
    branches: [ "main", "open_source" ]
  merge_group:
    types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # check out
      - name: Checkout repository
        uses: actions/checkout@v3

      # install rust tools
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clone ethereum/tests repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ethereum/tests.git tests/ethereum/tests

      - name: Run tests
        run: cargo test --test ethereum
